# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-29 13:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='popularity',
            new_name='99popularity',
        ),
    ]
