# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-30 05:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0004_auto_20180130_0717'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genere',
            new_name='Genre',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='genere',
            new_name='genre',
        ),
    ]
