# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-30 06:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0005_auto_20180130_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='director',
            new_name='director_id',
        ),
    ]
